"""initial schema

Revision ID: 4392f2440a28
Revises: 39fb7f0bb56c
Create Date: 2026-04-22 15:40:24.174697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4392f2440a28'
down_revision: Union[str, None] = '39fb7f0bb56c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
