/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as ActivityLogsRouteImport } from './routes/activity-logs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorsIndexRouteImport } from './routes/vendors/index'
import { Route as RfqIndexRouteImport } from './routes/rfq/index'
import { Route as QuotationsIndexRouteImport } from './routes/quotations/index'
import { Route as PurchaseOrdersIndexRouteImport } from './routes/purchase-orders/index'
import { Route as InvoicesIndexRouteImport } from './routes/invoices/index'
import { Route as VendorsAddRouteImport } from './routes/vendors/add'
import { Route as VendorsIdRouteImport } from './routes/vendors/$id'
import { Route as RfqCreateRouteImport } from './routes/rfq/create'
import { Route as PurchaseOrdersIdRouteImport } from './routes/purchase-orders/$id'
import { Route as InvoicesCreateRouteImport } from './routes/invoices/create'
import { Route as InvoicesIdRouteImport } from './routes/invoices/$id'
import { Route as RfqIdIndexRouteImport } from './routes/rfq/$id/index'
import { Route as VendorsEditIdRouteImport } from './routes/vendors/edit/$id'
import { Route as RfqIdCompareRouteImport } from './routes/rfq/$id/compare'
import { Route as QuotationsSubmitRfqIdRouteImport } from './routes/quotations/submit/$rfqId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityLogsRoute = ActivityLogsRouteImport.update({
  id: '/activity-logs',
  path: '/activity-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsIndexRoute = VendorsIndexRouteImport.update({
  id: '/vendors/',
  path: '/vendors/',
  getParentRoute: () => rootRouteImport,
} as any)
const RfqIndexRoute = RfqIndexRouteImport.update({
  id: '/rfq/',
  path: '/rfq/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationsIndexRoute = QuotationsIndexRouteImport.update({
  id: '/quotations/',
  path: '/quotations/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersIndexRoute = PurchaseOrdersIndexRouteImport.update({
  id: '/purchase-orders/',
  path: '/purchase-orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsAddRoute = VendorsAddRouteImport.update({
  id: '/vendors/add',
  path: '/vendors/add',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsIdRoute = VendorsIdRouteImport.update({
  id: '/vendors/$id',
  path: '/vendors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RfqCreateRoute = RfqCreateRouteImport.update({
  id: '/rfq/create',
  path: '/rfq/create',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersIdRoute = PurchaseOrdersIdRouteImport.update({
  id: '/purchase-orders/$id',
  path: '/purchase-orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesCreateRoute = InvoicesCreateRouteImport.update({
  id: '/invoices/create',
  path: '/invoices/create',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIdRoute = InvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RfqIdIndexRoute = RfqIdIndexRouteImport.update({
  id: '/rfq/$id/',
  path: '/rfq/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsEditIdRoute = VendorsEditIdRouteImport.update({
  id: '/vendors/edit/$id',
  path: '/vendors/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RfqIdCompareRoute = RfqIdCompareRouteImport.update({
  id: '/rfq/$id/compare',
  path: '/rfq/$id/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationsSubmitRfqIdRoute = QuotationsSubmitRfqIdRouteImport.update({
  id: '/quotations/submit/$rfqId',
  path: '/quotations/submit/$rfqId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity-logs': typeof ActivityLogsRoute
  '/approvals': typeof ApprovalsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/invoices/create': typeof InvoicesCreateRoute
  '/purchase-orders/$id': typeof PurchaseOrdersIdRoute
  '/rfq/create': typeof RfqCreateRoute
  '/vendors/$id': typeof VendorsIdRoute
  '/vendors/add': typeof VendorsAddRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/purchase-orders/': typeof PurchaseOrdersIndexRoute
  '/quotations/': typeof QuotationsIndexRoute
  '/rfq/': typeof RfqIndexRoute
  '/vendors/': typeof VendorsIndexRoute
  '/quotations/submit/$rfqId': typeof QuotationsSubmitRfqIdRoute
  '/rfq/$id/compare': typeof RfqIdCompareRoute
  '/vendors/edit/$id': typeof VendorsEditIdRoute
  '/rfq/$id/': typeof RfqIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity-logs': typeof ActivityLogsRoute
  '/approvals': typeof ApprovalsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/invoices/create': typeof InvoicesCreateRoute
  '/purchase-orders/$id': typeof PurchaseOrdersIdRoute
  '/rfq/create': typeof RfqCreateRoute
  '/vendors/$id': typeof VendorsIdRoute
  '/vendors/add': typeof VendorsAddRoute
  '/invoices': typeof InvoicesIndexRoute
  '/purchase-orders': typeof PurchaseOrdersIndexRoute
  '/quotations': typeof QuotationsIndexRoute
  '/rfq': typeof RfqIndexRoute
  '/vendors': typeof VendorsIndexRoute
  '/quotations/submit/$rfqId': typeof QuotationsSubmitRfqIdRoute
  '/rfq/$id/compare': typeof RfqIdCompareRoute
  '/vendors/edit/$id': typeof VendorsEditIdRoute
  '/rfq/$id': typeof RfqIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity-logs': typeof ActivityLogsRoute
  '/approvals': typeof ApprovalsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/invoices/create': typeof InvoicesCreateRoute
  '/purchase-orders/$id': typeof PurchaseOrdersIdRoute
  '/rfq/create': typeof RfqCreateRoute
  '/vendors/$id': typeof VendorsIdRoute
  '/vendors/add': typeof VendorsAddRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/purchase-orders/': typeof PurchaseOrdersIndexRoute
  '/quotations/': typeof QuotationsIndexRoute
  '/rfq/': typeof RfqIndexRoute
  '/vendors/': typeof VendorsIndexRoute
  '/quotations/submit/$rfqId': typeof QuotationsSubmitRfqIdRoute
  '/rfq/$id/compare': typeof RfqIdCompareRoute
  '/vendors/edit/$id': typeof VendorsEditIdRoute
  '/rfq/$id/': typeof RfqIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity-logs'
    | '/approvals'
    | '/dashboard'
    | '/login'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/verify-email'
    | '/invoices/$id'
    | '/invoices/create'
    | '/purchase-orders/$id'
    | '/rfq/create'
    | '/vendors/$id'
    | '/vendors/add'
    | '/invoices/'
    | '/purchase-orders/'
    | '/quotations/'
    | '/rfq/'
    | '/vendors/'
    | '/quotations/submit/$rfqId'
    | '/rfq/$id/compare'
    | '/vendors/edit/$id'
    | '/rfq/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity-logs'
    | '/approvals'
    | '/dashboard'
    | '/login'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/verify-email'
    | '/invoices/$id'
    | '/invoices/create'
    | '/purchase-orders/$id'
    | '/rfq/create'
    | '/vendors/$id'
    | '/vendors/add'
    | '/invoices'
    | '/purchase-orders'
    | '/quotations'
    | '/rfq'
    | '/vendors'
    | '/quotations/submit/$rfqId'
    | '/rfq/$id/compare'
    | '/vendors/edit/$id'
    | '/rfq/$id'
  id:
    | '__root__'
    | '/'
    | '/activity-logs'
    | '/approvals'
    | '/dashboard'
    | '/login'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/verify-email'
    | '/invoices/$id'
    | '/invoices/create'
    | '/purchase-orders/$id'
    | '/rfq/create'
    | '/vendors/$id'
    | '/vendors/add'
    | '/invoices/'
    | '/purchase-orders/'
    | '/quotations/'
    | '/rfq/'
    | '/vendors/'
    | '/quotations/submit/$rfqId'
    | '/rfq/$id/compare'
    | '/vendors/edit/$id'
    | '/rfq/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityLogsRoute: typeof ActivityLogsRoute
  ApprovalsRoute: typeof ApprovalsRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  InvoicesIdRoute: typeof InvoicesIdRoute
  InvoicesCreateRoute: typeof InvoicesCreateRoute
  PurchaseOrdersIdRoute: typeof PurchaseOrdersIdRoute
  RfqCreateRoute: typeof RfqCreateRoute
  VendorsIdRoute: typeof VendorsIdRoute
  VendorsAddRoute: typeof VendorsAddRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
  PurchaseOrdersIndexRoute: typeof PurchaseOrdersIndexRoute
  QuotationsIndexRoute: typeof QuotationsIndexRoute
  RfqIndexRoute: typeof RfqIndexRoute
  VendorsIndexRoute: typeof VendorsIndexRoute
  QuotationsSubmitRfqIdRoute: typeof QuotationsSubmitRfqIdRoute
  RfqIdCompareRoute: typeof RfqIdCompareRoute
  VendorsEditIdRoute: typeof VendorsEditIdRoute
  RfqIdIndexRoute: typeof RfqIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity-logs': {
      id: '/activity-logs'
      path: '/activity-logs'
      fullPath: '/activity-logs'
      preLoaderRoute: typeof ActivityLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/': {
      id: '/vendors/'
      path: '/vendors'
      fullPath: '/vendors/'
      preLoaderRoute: typeof VendorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfq/': {
      id: '/rfq/'
      path: '/rfq'
      fullPath: '/rfq/'
      preLoaderRoute: typeof RfqIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotations/': {
      id: '/quotations/'
      path: '/quotations'
      fullPath: '/quotations/'
      preLoaderRoute: typeof QuotationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders/': {
      id: '/purchase-orders/'
      path: '/purchase-orders'
      fullPath: '/purchase-orders/'
      preLoaderRoute: typeof PurchaseOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/add': {
      id: '/vendors/add'
      path: '/vendors/add'
      fullPath: '/vendors/add'
      preLoaderRoute: typeof VendorsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/$id': {
      id: '/vendors/$id'
      path: '/vendors/$id'
      fullPath: '/vendors/$id'
      preLoaderRoute: typeof VendorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfq/create': {
      id: '/rfq/create'
      path: '/rfq/create'
      fullPath: '/rfq/create'
      preLoaderRoute: typeof RfqCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders/$id': {
      id: '/purchase-orders/$id'
      path: '/purchase-orders/$id'
      fullPath: '/purchase-orders/$id'
      preLoaderRoute: typeof PurchaseOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/create': {
      id: '/invoices/create'
      path: '/invoices/create'
      fullPath: '/invoices/create'
      preLoaderRoute: typeof InvoicesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$id': {
      id: '/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof InvoicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfq/$id/': {
      id: '/rfq/$id/'
      path: '/rfq/$id'
      fullPath: '/rfq/$id/'
      preLoaderRoute: typeof RfqIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/edit/$id': {
      id: '/vendors/edit/$id'
      path: '/vendors/edit/$id'
      fullPath: '/vendors/edit/$id'
      preLoaderRoute: typeof VendorsEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfq/$id/compare': {
      id: '/rfq/$id/compare'
      path: '/rfq/$id/compare'
      fullPath: '/rfq/$id/compare'
      preLoaderRoute: typeof RfqIdCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotations/submit/$rfqId': {
      id: '/quotations/submit/$rfqId'
      path: '/quotations/submit/$rfqId'
      fullPath: '/quotations/submit/$rfqId'
      preLoaderRoute: typeof QuotationsSubmitRfqIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityLogsRoute: ActivityLogsRoute,
  ApprovalsRoute: ApprovalsRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  InvoicesIdRoute: InvoicesIdRoute,
  InvoicesCreateRoute: InvoicesCreateRoute,
  PurchaseOrdersIdRoute: PurchaseOrdersIdRoute,
  RfqCreateRoute: RfqCreateRoute,
  VendorsIdRoute: VendorsIdRoute,
  VendorsAddRoute: VendorsAddRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
  PurchaseOrdersIndexRoute: PurchaseOrdersIndexRoute,
  QuotationsIndexRoute: QuotationsIndexRoute,
  RfqIndexRoute: RfqIndexRoute,
  VendorsIndexRoute: VendorsIndexRoute,
  QuotationsSubmitRfqIdRoute: QuotationsSubmitRfqIdRoute,
  RfqIdCompareRoute: RfqIdCompareRoute,
  VendorsEditIdRoute: VendorsEditIdRoute,
  RfqIdIndexRoute: RfqIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
